### ISSUE TITLE
Contract execution should cost a predictable amount

### ISSUE THREAD

**Issue by MParlikar** [CasperLabs/Governance#1]
In the Ethereum Gas model, contract execution costs are not fixed or predictable. This makes running a viable business (with budgeted transaction costs) impossible. What needs to be done:

- Propose alternative models for transaction execution costs.
- Create a model in Excel or a simulation that would demonstrate how this would work

**Comment by J8Q2** [comment]
Fixed gas costs make the chain more attackable (spamming) and what global asset would it be pegged to (can't be US centric) and what would the oracle be for the price feed? Would a soft, code based solution like bitcoin blocktimes make sense?  Also I guess we will need to see how the oscillation between low stock to flow vs high stock to flow impacts the usability of the chain when liquidity profiles change on full PoS compared to PoW and with contract lock ups such as Maker.
