### ISSUE TITLE
Name Option #10

### ISSUE THREAD

**Issue by MParlikar** [CasperLabs/Governance#12]
Chain Name: Snowball
Token Name: Ice
Token Symbol: ICE
Name for gas: vapor

**Comment by AlexKelly33** [comment]
I love the imagery of an ice crystal falling from the sky collecting vapor to make a snowflake. When the snowflakes land, the community makes a snowball and throws it down a never ending hill where it will continuously grow over time as it rolls.

**Comment by adamhackbarth** [comment]
Of course there is that classic scene in Clerks: https://www.youtube.com/watch?v=m_A58231NFk

I kind of like the whole Quiet Riot of two opposites being smashed together. How about Snowfire?

**Comment by ChrisYuYu** [comment]
snowball    it's ok

**Comment by Ojimadu** [comment]
Thanks everyone for the suggestions. A name has been chosen by the team so we can close this out. Please refer to issue #5
