### ISSUE TITLE
Naming Option 17

### ISSUE THREAD

**Issue by thebrowner** [CasperLabs/Governance#19]
Chain Name: MUNE
Token name : U
Token Symbol: MUU (pronounced MEW)
Name for Gas: toll
 
MUNE meaning community. Shorten version of commune. A community of developers, a community of founders, a community for innovation, a community that is building on the brilliant idea of blockchain, a community that goes beyond one protocol but a collective that collaborate, share ideas in order to bring this movement forward knowing that this technology is the future and it will take more then one individual effort.  Its more collaborative then competitive, as we are driving each others innovation. A nice definition of a community or comMUNE.

**Comment by Ojimadu** [comment]
Thanks everyone for the suggestions. A name has been chosen by the team so we can close this out. Please refer to issue #5
