### ISSUE TITLE
"Three" legged stool governance issue

### ISSUE THREAD

**Issue by J8Q2** [CasperLabs/Governance#2]
Assuming there are several indispensable legs to the protocol stool (Developers, Validators, Applications, etc) what protections in the governance model will there be to ensure a proposal that passes with a high risk of disenfranchisement of a given leg of the stool (Apps & Validators with 60% of constituent votes FOR; while 95% of Devs vote AGAINST) is not treated the same as one that passes with relative low risk?  Veto supermajority for each leg (segment) of the community or at least a threshold that forces a 2nd round of voting possibly with different procedures?  Another approach is to not give each segment of the community an equal vote yet this of course rises it's own set of issues yet it could be a step in the right direction as i assume that over the life cycle of a given protocol the importance of each segment of the community may vary even though they are all necessary and thus all deserve some form of vote.

**Comment by MParlikar** [comment]
It sounds like what you are mentioning is 'what is the threshold for a motion to pass at the board'?  This is not something that I have specified, and I don't know the answer.  2/3rds majority?  Perhaps if one constituency strongly disagrees, they can force the motion to require more consensus?  3/4?  I"m not sure that 1 constituency should be able to censor a motion.  That being said, if the Core devs disagree, how prudent is that motion?  Seems like a bad thing?

**Comment by J8Q2** [comment]
Agreed.  The balance that would seem to be needed is one that avoids censorship yet also avoids significant disenfranchisement of any particular constituency that is vital to the prosperity/survival of the protocol.  The added level of complexity would seem to be how one would weight how vital a given constituency is to the protocol not only at first but over time.  For example while Ethereum still can't write off the interests of miners, over time the weight miners should have in the governence process should probably decline as Ethereum attempts to move to PoS.
