### ISSUE TITLE
Name Option 1

### ISSUE THREAD

**Issue by MParlikar** [CasperLabs/Governance#3]
Name of the Protocol: CASPER
Name of Token: BOO
Token Symbol: BOO
Name for 'gas': plasm

Please vote using a reaction

**Comment by MParlikar** [comment]
Please vote by using a reaction

**Comment by colga63768** [comment]
At first I down voted this, but after giving it some thought, I kind of like boo for a token symbol 🤗stands out - BOO 👻 we’re here and transparent - just my 2 boos 😉

**Comment by Ojimadu** [comment]
Thanks everyone for the suggestions. A name has been chosen by the team so we can close this out. Please refer to issue #5
